### ISSUE TITLE
Add theme picker option

### ISSUE THREAD

**Issue by pawank0411** [Pawan0411/AWOL#10]
Present scenario consists of only 2 basic themes (Light mode and dark mode).
Add a option to select different themes.

reference
https://www.androidpolice.com/2016/03/08/yahoo-mail-introduces-themes-and-colors-to-customize-the-look-of-all-your-inboxes/

**Comment by GAyan17** [comment]
Hello, could you please elaborate more about the issue to resolve it, I'm kind of new to the open source and don't know much, but I like to contribute.

**Comment by pawank0411** [comment]
@GAyan17 Please go to reference link provided above.
You need to add a theme picker screen.

**Comment by Piyush7890** [comment]
I would like to work on this issue. Could you please assign me for this issue?

**Comment by pawank0411** [comment]
@Piyush7890 you can work on this.

**Comment by Piyush7890** [comment]
What exactly is expected here? I mean i can see that you have a switch preference to toggle between dark and light theme. Are you going to add more themes in future?

**Comment by pawank0411** [comment]
Add a item in Navigation Drawer as `theme Selector`.
You need to add more themes to it.

see the reference given below.
 https://www.androidpolice.com/2016/03/08/yahoo-mail-introduces-themes-and-colors-to-customize-the-look-of-all-your-inboxes/

**Comment by pawank0411** [comment]
@Piyush7890 any update?

**Comment by Piyush7890** [comment]
I have few doubts.
 Suppose the theme is changed to orange, so what colors are suppose to change in the screenshot
![unnamed](https://user-images.githubusercontent.com/25117135/66124783-f2d6d780-e602-11e9-9317-88aa113d9362.jpg)

**Comment by pawank0411** [comment]
you can check this 
https://kuler.adobe.com/create/color-wheel/?

**Comment by pawank0411** [comment]
My suggestion for light colors,
just change the color of toolbar and keep the rest as white.

And for dark color, change the color of toolbar and keep the rest as black.

**Comment by Pawan0411** [comment]
This is actually what I want

**Comment by pawank0411** [comment]
hope so your doubt is now clear and you'll start working on it asap.

**Comment by Piyush7890** [comment]
Yep, got it

**Comment by Piyush7890** [comment]
Do you have to demo account to login??
I don't have the login credentials so I cant test the themes

**Comment by pawank0411** [comment]
```
username 12345
password 12345
```

**Comment by Piyush7890** [comment]
This is what i came up with.
![Screenshot_20191004-120855](https://user-images.githubusercontent.com/25117135/66186657-7692d180-e6a0-11e9-903f-28f9ebf97f6b.jpeg)
![Screenshot_20191004-121059](https://user-images.githubusercontent.com/25117135/66186660-77c3fe80-e6a0-11e9-813d-d5702c1bc782.jpeg)

**Comment by Piyush7890** [comment]
What about the green icons in the toolbar like the hamburger icon and the share icon.
Now if the theme is changed to orange, the green color wont suit on orange toolbar

**Comment by pawank0411** [comment]
Good work @Piyush7890,
yes for toolbar icons would it be better if we change the colors according to theme color, like for orange color make the hamburger and share icon as orange color.

**Comment by Piyush7890** [comment]
so if i make the hamburger and share icon to orange then what about the toolbar, because previously you said for light colors change the toolbar color.
I guess it should be complimentary like for Orange theme, toolbar color will be orange and the icon colors will be white.

**Comment by pawank0411** [comment]
okay, that's fine.

**Comment by pawank0411** [comment]
icons white,
toolbar color according to theme color

**Comment by pawank0411** [comment]
@Piyush7890 Good work

**Comment by Piyush7890** [comment]
Thanks!
