### ISSUE TITLE
UI change for plan a bunk section

### ISSUE THREAD

**Issue by pawank0411** [Pawan0411/AWOL#12]
UI enhancement for `Plan@bunk` section.
- Add a toolbar 

- Instead of spinner add a drop down list.
reference : https://www.androidcode.ninja/show-listview-as-drop-down-android/

**Comment by Piyush789** [comment]
I ll take this one.

**Comment by pawank0411** [comment]
@Piyush789 you can work on this.

**Comment by pawank0411** [comment]
any updates @Piyush789

**Comment by pawank0411** [comment]
fixed.
