### ISSUE TITLE
storing each user's data as cache. 

### ISSUE THREAD

**Issue by pawank0411** [Pawan0411/AWOL#15]
store the details of each user that logs in as cache and persist it even after logging out

**Comment by tejasvisoi** [comment]
I can help!

**Comment by tejasvisoi** [comment]
Which all fields require saving?

**Comment by pawank0411** [comment]
Attendance of all the subjects with all the details regarding the subject like subject name, total number of theory an lab classes and total number of absents.

For more info contact me here : 
https://www.linkedin.com/in/pawan-kumar-gorai-b79508161/

**Comment by pawank0411** [comment]
fixed.
