### ISSUE TITLE
Add a splash screen

### ISSUE THREAD

**Issue by pawank0411** [Pawan0411/AWOL#17]
Redesign the icon , so that it will be supported for Adaptive icon.

**Comment by Darshpreet2000** [comment]
What should I display in Splash Screen?

**Comment by pawank0411** [comment]
The app icon, redesign the present icon and use it in splash Screen

**Comment by Darshpreet2000** [comment]
![Screenshot_2019-12-06-16-03-43-99_1e6211f6d6e11e53b6c81e7125479456](https://user-images.githubusercontent.com/47180477/70316700-3ee00b80-1842-11ea-8f1f-ce78166b7b07.png)

**Comment by Darshpreet2000** [comment]
Is it okay??

**Comment by pawank0411** [comment]
@Darshpreet2000 college image is getting blurred.
Don't use it. Let's go with simple college logo. 👍

**Comment by Darshpreet2000** [comment]
![Screenshot_2019-12-07-15-44-39-94_8c89d4cb44e1d26305014d79361b59bc](https://user-images.githubusercontent.com/47180477/70372707-a8c2e880-1908-11ea-87bd-1ba1cfd5fc2d.png)

**Comment by Darshpreet2000** [comment]
Is it Okay?

**Comment by Darshpreet2000** [comment]
should I change app icon to this logo

**Comment by pawank0411** [comment]
yes, redesign it and Change

**Comment by pawank0411** [comment]
> 
> 
> ![Screenshot_2019-12-07-15-44-39-94_8c89d4cb44e1d26305014d79361b59bc](https://user-images.githubusercontent.com/47180477/70372707-a8c2e880-1908-11ea-87bd-1ba1cfd5fc2d.png)

@Darshpreet2000 background color should get changed when user switches from light mode to dark mode.
