### ISSUE TITLE
add a screen "Attendance not available"

### ISSUE THREAD

**Issue by pawank0411** [Pawan0411/AWOL#9]
Handle the exception inside Bunk class and home Class.
Instead add a screen "Attendance not available".

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{mohit.codex_iter.www.awol/mohit.codex_iter.www.awol.Bunk}: java.lang.NullPointerException: Attempt to get length of null array`

```
Caused by java.lang.NullPointerException: Attempt to read from null array
       at mohit.codex_iter.www.awol.home.onCreate + 125(home.java:125)
```

**Comment by anandsankritya** [comment]
can i take this?

**Comment by pawank0411** [comment]
Yes @snkritya  you can work on this.

**Comment by anandsankritya** [comment]
how can i reproduce the bug?

**Comment by pawank0411** [comment]
Testing credentials
```
username : 1234
password : 1234
```

**Note : There's no attendance in this account**

**Comment by anandsankritya** [comment]
couldn't able to catch the bug?

**Comment by pawank0411** [comment]
> 
> 
> couldn't able to catch the bug?

what?

**Comment by pawank0411** [comment]
@snkritya any update?

**Comment by anandsankritya** [comment]
issue already been handled in master branch
